autoconf-archive/autoconf-archive

m4/ax_valgrind_check.m4
Support running the macro in projects which have not used LT_INIT.
=> ax_valgrind_check: Support running without libtool

m4/ax_compiler_flags_cflags.m4
While porting Yelp to use AX_COMPILER_FLAGS (from GNOME_COMPILE_WARNINGS), I tried supplying extra base compiler flags and noticed that they were not applied. After checking with Philip, it seems that the indexes on the AX_COMPILER_FLAGS_CFLAGS macro were not correct, after splitting the macro out from AC_COMPILER_FLAGS.
Fix the indexes so that the extra flags are applied.
=> ax_compiler_flags_cflags: Fix argument indexes

m4/ax_compiler_flags.m4, m4/ax_compiler_flags_cxxflags.m4
In EasyTAG, I use C and C++ within the same code base, and it helps to distinguish between the (quite overlapping) sets of warning flags for each compiler. Add a new AX_COMPILER_FLAGS_CXXFLAGS macro, based on AX_COMPILER_FLAGS_CFLAGS, and use it within AX_COMPILER_FLAGS to AC_SUBST the available warnings as WARN_CFLAGS. Take extra warnings from the supplied EXTRA-*-CFLAGS variables, which may or may not be the best approach, as most warnings are common between the C and C++ compilers, but some are not.
=> ax_compiler_flags: Add C++ compiler warning checks

m4/ax_compiler_flags.m4, m4/ax_compiler_flags_cflags.m4, m4/ax_compiler_flags_cxxflags.m4
Add a --disable-Werror option to unconditionally disable -Werror, independently of the warning level set with --enable-compile-warnings.
Minor fix for disabling some compiler warnings when used in the presence of a build bot which adds its own flags.
=> ax_compiler_flags: Add a --disable-Werror option

bootstrap.sh
When building autoconf-archive using build bots or JHBuild, it is quite
desirable to have a single command which will bootstrap the entire build
process, up to the point where `make` can be run.
bootstrap.sh is supposed to do this, but will fail if gnulib is not
present. Add a --copy option which will automatically clone gnulib into
the source directory if it’s not present.
=> bootstrap.sh: Support a --copy option to automatically clone gnulib

m4/ax_is_release.m4
The are various projects that use the micro version of $PACKAGE_VERSION
as an indication of whether the code is a release or if it's a snapshot
of the source under revision control.
The micro-version policy follows the existing minor-version policy in
spirit, if not in regular expression.
Signed-off-by: Emmanuele Bassi <ebassi@gnome.org>
=> ax-is-release: Add micro-version policy

m4/ax_boost_base.m4
Native Windows versions of Boost (for Visual C++) have a different
layout to other platforms. Typically, one has:
<root>\boost\version.hpp
This patch adds support for header only libraries.
=> AX_BOOST_BASE: Support for native Windows header only libraries

m4/ax_path_generic.m4
ax_path_generic.m4 fix when the _CFLAGS and _LIBS are provided and they
contain a space
For example:
./configure PCRE_LIBS='-L/home/me/pcre/lib -lpcre'
Patch also contains a portability fix from @vadz:
Use POSIX "=" instead of "==" which is not supported at least by FreeBSD
/bin/sh.
=> AX_PATH_GENERIC fixes for flags containing spaces

m4/ax_python_module_version.m4
The Python module version macro builds on top of the existing Python
module macro authored by Andrew Collier. The Python module macro checks
that a Python module is installed, and the Python module version macro
tests that a Python module is installed at a given version or higher.
=> ax_python_module_version: Add initial macro.

m4/ax_python_module.m4, m4/ax_python_module_version.m4
Permit dependency checking of both Python 2 and Python 3 modules.
=> ax_python_module[_version]: Add Python 3 support.

m4/ax_cxx_compile_stdcxx_11.m4
This compiler needs +std=c++11 to enable C++11 mode:
http://h21007.www2.hp.com/portal/download/files/unprot/aCxx/PDF_Release_Notes/769149-001.pdf
We've just switched Xapian (http://xapian.org/) to requiring C++11, so I am going through checking for any options needed to enable C++11 support in compilers people have previously reported success at building Xapian with.  Unfortunately I don't have access to most of these compilers myself, so I haven't been able to verify that this change enables current aCC to compile the test program the macro uses.
This document seems to suggest aCC is OK except for lacking support for `override`:
http://h21007.www2.hp.com/portal/site/dspp/menuitem.863c3e4cbcdc3f3515b49c108973a801?ciid=887a551fac19b410VgnVCM200000a460ea10RCRD
Despite this, I'm proposing …
=> ax_cxx_compile_stdcxx_11.m4: Support HP aCC

m4/ax_prog_bison_version.m4
Valid from Bison v1.29b until now[1].
[1]http://git.savannah.gnu.org/cgit/bison.git/commit/?id=e79137accc7ea0352cd4677ff22818f9c68d4eab
=> Add GNU Bison version check

m4/ax_cxx_compile_stdcxx_11.m4
Some compilers pass the other tests while not implementing this part of the C++11 specification. The test used also does not cause warnings with GCC or Clang, and can be used with -Werror.
After this change, GCC 4.7 no longer passes the tests. This macro is about compiler support, not standard library support, but the libstdc++ that comes with GCC 4.7 doesn't support emplace on standard library containers, so many C++11 programs would fail at compile-time on most systems using GCC 4.7.
This is my first autoconf archive submission, so I'm not sure if there's anything else I need to add.
Cross-ref openstreetmap/osm2pgsql#434
=> Check for attribute support with C++11 macro

m4/ax_gnu_autotest.m4
Synopsis:
Sets up one or multiple GNU Autotest test suites.
Brief description:
* Write tests/testsuite.at as normal
* Add to configure.ac: AX_GNU_AUTOTEST
* Add to Makefile.am or Makefile.in in top_srcdir: @AX_GNU_AUTOTEST_DEFAULT@
* autoreconf && ./configure && make check
Authors:
* Olaf Mandel
License:
All-permissive license
=> Add AX_GNU_AUTOTEST macro

m4/ax_compiler_flags_ldflags.m4
Not all compilers will verify the correctness of flags to the linker, so we need to explicitly use the linker when verifying flags.
=> AX_COMPILER_FLAGS_LDFLAGS: use AX_APPEND_LINK_FLAGS

m4/ax_cxx_compile_stdcxx_11.m4
Cray Compilation Environment 8.4 has full C++11 support through
"-h std=c++11" command line switch that we didn't test against
=> AX_CXX_COMPILE_STDCXX_11: Support for Cray's crayCC compiler (CCE 8.4)

m4/ax_lib_hdf5.m4
The test uses the C compiler wrapper, so tell autoconf that that should be the current language. Otherwise, you will get a warning if the current language is not C similar to:
```
configure.ac:237: warning: AC_LANG_PREPROC(Fortran): No preprocessor defined for Fortran
../../lib/autoconf/fortran.m4:245: AC_LANG_PREPROC(Fortran) is expanded from...
../../lib/autoconf/lang.m4:372: AC_LANG_PREPROC_REQUIRE is expanded from...
../../lib/autoconf/general.m4:2518: AC_PREPROC_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/m4sugar/m4sh.m4:385: AS_REQUIRE is expanded from...
../../lib/autoconf/general.m4:181: AC_REQUIRE_SHELL_FN is expanded from...
../../lib/autoconf/headers.m4:129: _AC_CHECK_HEADER_MONGREL is expanded from... …
```
=> Push C language before testing HDF5 libraries.

m4/ax_code_coverage.m4
This version is in Debian now and seems to work fine with the existing macros.
=> Add 1.12 to list of lcov versions.

m4/ax_with_curses_extra.m4
Found bug where when _AX_WITH_CURSES_CHECKEXTRA is called a second time
on the same library, e.g. ncurses, the previous setting of
_AX_WITH_CURSES_CHECKEXTRA_cv_var to 'yes' would be changed to 'no' just
due to the tested header file not being available on the second pass.
This was found when AX_WITH_CURSES has 'with_ncurses' set to 'yes' and
'with_ncursesw' set to 'no' forcing _AX_WITH_CURSES_CHECKEXTRA to be
called twice in succession since ax_cv_curses_which is set to 'ncurses'
and the panel.h header file is tested as ncurses/panel.h and panel.h.
The system in question is OpenSuSE LEAP 42.1 which installs
/usr/include/ncurses/panel.h and not /usr/include/panel.h.
=> Fix second pass bug in _AX_WITH_CURSES_CHECKEXTRA

m4/ax_gcc_x86_cpuid.m4
The problem is that the EBX register cannot be used when position independent code is being generated.
The solutions to save and restore the EBX register.  See, e.g.:
http://stackoverflow.com/questions/12221646/how-to-call-cpuid-instruction-in-a-mac-framework
=> fix AX_GCC_X86_CPUID/AX_GCC_X86_CPUID_COUNT for 32-bit PIC compilations

m4/ax_boost_system.m4
Newer version of boost::system have a breaking change that makes
the test on ax_boost_system fail even though the library is
present.
Changed the test to use another construct that did not change. Also
reseted the "CXX_FLAG" to an empty value in case of it having a
"-Werror" that also makes the test break.
----
this update "works on my box" but I have limited ability to test on older versions of boost or with different flags combinations.
=> Fix ax_boost_system for new versions of boost.

m4/ax_check_gir_symbols_gjs.m4, m4/ax_check_girs_gjs.m4, m4/ax_prog_gjs.m4
This adds three macros to the library:
AX_PROG_GJS - Check for the GJS JavaScript interpreter
AX_CHECK_GIRS_GJS - Check for importability of GObject introspection
module(s) in GJS
AX_CHECK_GIR_SYMBOLS_GJS - Check for the presence of particular symbols
in a GObject introspection module imported into GJS
=> Add GJS macros

m4/ax_code_coverage.m4, m4/ax_valgrind_check.m4
DISTCHECK_CONFIGURE_FLAGS (no prefix) is for the user to override the
distcheck configure flags. The AM_-prefixed version is for build systems
to use.
https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html
=> Use AM_DISTCHECK_CONFIGURE_FLAGS instead of DISTCHECK_CONFIGURE_FLAGS

m4/ax_code_coverage.m4
This contains the following Savannah patches:
* [AX_CODE_COVERAGE: add BRANCH_COVERAGE variable](https://savannah.gnu.org/patch/index.php?8920)
* [AX_CODE_COVERAGE: fix invalid chars in testname](https://savannah.gnu.org/patch/index.php?8921)
=> 2 patches for code coverage

m4/ax_valgrind_check.m4
This contains the following Savannah patches:
* [AX_VALGRIND_CHECK: clean up configure message](https://savannah.gnu.org/patch/?8930)
* [AX_VALGRIND_CHECK: fix logic around AC_CHECK_PROG](https://savannah.gnu.org/patch/?8931)
* [AX_VALGRIND_CHECK: quote VALGRIND_CHECK_RULES](https://savannah.gnu.org/patch/?8932)
=> 3 patches for valgrind check

m4/ax_gnu_autotest.m4
Some static strings in AC_SUBST() were underquoted: fix that.
This contains the following Savannah patch:
* [AX_GNU_AUTOTEST: quote some static strings](https://savannah.gnu.org/patch/?8928)
=> AX_GNU_AUTOTEST: quote some static strings

m4/ax_prog_doxygen.m4
Quote the DX_RULES assignment to prevent some other M4 macro from modifying the text. Also transition from direct if-statements to AS_IF for the same reasons: to prevent undesired macro replacements.
This contains the following Savannah patch:
* [AX_PROG_DOXYGEN: quote DX_RULES](https://savannah.gnu.org/patch/?8929)
=> AX_PROG_DOXYGEN: quote DX_RULES

m4/ax_code_coverage.m4
Quote the CODE_COVERAGE_RULES assignment to prevent some other
M4 macro from modifying the static text.
This contains the following Savannah patch:
* [AX_CODE_COVERAGE: quote CODE_COVERAGE_RULES](https://savannah.gnu.org/patch/?8927)
=> AX_CODE_COVERAGE: quote CODE_COVERAGE_RULES

m4/ax_code_coverage.m4
Simply define CODE_COVERAGE_CXXFLAGS with the same value as
CODE_COVERAGE_CFLAGS. Tested on libzmq (a C++ project).
=> Add C++ support to ax_code_coverage.m4

m4/ax_check_gl.m4, m4/ax_check_glu.m4, m4/ax_check_glut.m4, m4/ax_restore_flags_with_prefix.m4, m4/ax_save_flags_with_prefix.m4
Main features added:
- Support action-if-found and not-found hook
- Export HAVE_GL, HAVE_GLU, and HAVE_GLUT preprocessor symbol
- Add necessary flags to CFLAGS/LIBS by default, but can be disabled by
overwritting action-if-found hook.
- Fail the configure script if lib not found. This feature can be disabled by
overwritting action-if-not-found hook
- Fix problems on Mac OSX. Been tested on Linux (Ubuntu) and OSX
- Use --with-xquartz-gl instead of --with-gl=x for using X11 on OSX
Two new macros added:
- ax_save_flags_with_prefix.m4: save flags and pushes flag with prefix to the
flag.
AX_SAVE_FLAGS_WITH_PREFIX([GL],[[CFLAGS],[LIBS]]) would expands to
gl_saved_flag_cflags="$CFLAGS"
gl_saved_flag_libs="$LIBS"
CFLAGS="$GL_CFLAGS $CFLAGS"
LIBS="$GL_LIBS $LIBS"
- ax_restore_flags_with_prefix.m4: …
=> Improved three opengl autoconf macros

m4/ax_valgrind_check.m4
Often not all tools can be ran cleanly on a codebase. This means that
make check-valgrind will never complete successfully, which is a
problem especially when using ax_valgrind_check on a continous
integration system.
=> ax_valgrind_check: add a target for each tool

m4/ax_cxx_compile_stdcxx.m4, m4/ax_cxx_compile_stdcxx_11.m4, m4/ax_cxx_compile_stdcxx_14.m4
I'm currently facing this issue: I'm using the `AX_CXX_COMPILE_STDCXX_11` macro (which in turn uses `AX_CXX_COMPILE_STDCXX`) to check for C++11 compiler support.  If C++11 compiler support is detected, this macro sets `CXX` by appending the relevant switch:
```
CXX="$CXX $switch"
```
So far, so good.  Problem is, other variables are evaluated in an earlier stage from `CXX`, such as `CXXCPP` in `AC_PROG_CXXCPP`:
```
[...snip...]
if test -z "$CXXCPP"; then
AC_CACHE_VAL(ac_cv_prog_CXXCPP,
[dnl
for CXXCPP in "$CXX -E" "/lib/cpp"
do
_AC_PROG_PREPROC_WORKS_IFELSE([break])
done
ac_cv_prog_CXXCPP=$CXXCPP
])dnl
CXXCPP=$ac_cv_prog_CXXCPP
else
ac_cv_prog_CXXCPP=$CXXCPP
fi
[...snip...]
```
After a macro sets `CXX` (such as `AX_CXX_COMPILE_STDCXX_11` does), I found no (clean) way to have Autoconf …
=> Update CXXCPP after updating CXX.

m4/ax_with_curses.m4
Dear Peter,
I've modernized the **AX_WITH_CURSES** macro, which was in dire need of updating. Some of the improvements:
1. We now first try if we can infer the required flags with pkg-config. Information from .pc is more authoritative than just the flags we have been throwing at it. Unfortunately, pkg-config files in ncurses are optional, so we still retain the old fallback detection.
2. The fallback detection was broken with ncurses 6, which has shuffled around symbols and generally requires `-ltinfo` linking for anything more than just `initscr()`. We now also try linking with `-ltinfo` in case linking with `-lncurses{,w}` fails the first time.
This change is rather important, as the whole ecosystem is suffering massive build system breakage due to the required `-ltinfo` flag. I'll try …
=> AX_WITH_CURSES: Enable pkg-config support

m4/ax_check_x86_features.m4, m4/ax_gcc_x86_cpu_supports.m4
Added two macros: ax_check_x86_features.m4, and ax_gcc_x86_cpu_supports.m4
It checks if the host cpu supports various instruction set: mmx, sse, popcnt,
avx, avx2, etc. If the instruction were supported, it would export
HAVE_XXX_INSTRUCTIONS C preprocessor macros and add the instruction set flag to
X86_FEATURES_CFLAGS variable. By default it would also set CFLAGS, but this can
be disabled by the ACTION-IF-FOUND hook.
The code were tested with real project.
=> macros for X86 instruction set tests

m4/ax_valgrind_check.m4
This is a collection of four patches three of which are connected to running only some of the supported valgrind tools:
* refactor new tool-rules: remove code duplication
* add disabling individual tools: add configure command-line options
* make disabling configurable: add AX_VALGRIND_DFLT() function
Also add support for silent rules.
=> AX_VALGRIND_CHECK: total of four patches

m4/ax_prog_doxygen.m4
Add the file doxygen_sqlite3.db to DX_CLEANFILES. This file is
generated by (some?) newer versions of doxygen.
=> AX_PROG_DOXYGEN: cleanup doxygen_sqlite3.db

m4/ax_code_coverage.m4
* Make the find command actually remove any *.gcda files left over
by lcov -z
* Also remove *.gcno files
* Make distclean remove all code-coverage-clean files as well
=> AX_CODE_COVERAGE: fix problems with (dist)clean

m4/ax_check_girs_gjs.m4
The error message printed when this macro failed to find what it was looking
for, was misleading: it implied that if you were looking for the Gtk-1.0 API then
installing the Gtk-3.0 API would do. That isn't the case, so fix the message.
=> ax_check_girs_gjs: Fix misleading error message

m4/ax_count_cpus.m4
Almost complete overwrite of AX_COUNT_CPUS.
Now detection is not limited to known platforms and should work on most current platforms.
Used locale-independent and machine-parseable commands if possible so results must be predictable and stable.
Macro now tries to detect currently enabled CPUs (it's possible in some OSes to disable specific CPU core).
Several methods are used for any platforms (at least three), for popular platforms can be used up to six detection methods so chances of success are really high. :smiley: 
Tested on Linuxes, FreeBSD, MSys2, MSys, Cygwin, MinGW, Solaris and Darwin.
Should correctly detect number of CPUs on current and previous OS versions and may detect on exotic platforms.
Added support for ACTION-IF-DETECTED and ACTION-IF-NOT-DETECTED so it's possible to …
=> AX_COUNT_CPUS overhaul 

m4/ax_have_qt.m4
Add "-s" to make arguments. Without, make's output (like "Entering directory")
gets assigned to output variables.
=> AX_HAVE_QT: Silent make for variable setting

m4/ax_cxx_compile_stdcxx_11.m4, m4/ax_cxx_compile_stdcxx_14.m4
The search path for `include` is the current working directory, so trying
to include other m4 files directly only works if they live in the same dir
as where you're running `aclocal`.  Otherwise we end up with errors like:
$ cd lcd4linux-0.10.1-RC2
$ aclocal
/usr/share/aclocal/ax_cxx_compile_stdcxx_14.m4:32: file 'ax_cxx_compile_stdcxx.m4' does not exist
Use the AX_REQUIRE_DEFINED macro instead to make sure the macro we want
exists.
=> fix include errors w/AX_CXX_COMPILE_STDCXX_1[14]

NEWS, m4/ax_with_curses.m4, m4/ax_with_curses_extra.m4
* Ultimately, ax_with_curses.m4 and ax_with_curses_extra.m4 should fall out of
use once ncurses pkg-config files have become ubiquitous in the ecosystem.
Until then, the precious variables have been renamed to match the style of
`PKG_CHECK_MODULES`, such that a later replacement of the macros can be
performed with a simple sed.
=> Update ax_with_curses.m4 and ax_with_curses_extra.m4 to match PKG_CHECK_MODULES style

m4/ax_check_openssl.m4
Some distros provide prefixed pkg-config. This patch ensures
the right tool is picked.
See https://www.gnu.org/software/autoconf/manual/autoconf.html#Generic-Programs
for details
=> AX_CHECK_OPENSSL: use AC_CHECK_TOOL for pkg-config

m4/ax_lib_hdf5.m4
I have a problem where I need to know whether HDF5 was built parallel or serial. I can take care of it in my configure.ac, so I would like the AX_LIB_HDF5 macro to set a variable I can test. The current variables don't reliably give me that information. So I updated the macro to return that information.
=> HDF5 type variable

m4/ax_open62541_path.m4
Get `configure`, `make distcheck` and e.g. `make check` to work seamlessly even if open62541 is not installed on the system: no more manual setting of `LD_LIBRARY_PATH`. For custom targets like `make check` to work, a newly defined Makefile variable must be used.
=> ax_open62541_path: two fixes for shared libraries

m4/ax_boost_base.m4
this is a typo correction of previous commit 1f9acf39e6b3
as per original patch from https://savannah.gnu.org/patch/index.php?8473
=> remove useless ppc64le trailing word in libsubdirs

m4/ax_prog_gjs.m4
This looks in pkg-config for the GJS executable, since the gjs-1.0
package provides it as a pkg-config variable. However, not all versions
of GJS do, so we fall back to checking in the path.
=> ax_prog_gjs: Look in pkg-config as well as path

m4/ax_lib_mysqlcppconn.m4
ax_lib_mysqlcppconn.m4 has a typo referencing CFLAGS. This typo prevents --with-libmysqlcppconn from being used.
=> Fix reference to LIBMYSQLCPPCONN_CXXFLAGS

m4/ax_openmp.m4
The latest intel compilers uses `-qopenmp` for openmp flags (they do still provide backwards compatibility
=> Updated OpenMP flag detection for latest Intel compilers

m4/ax_code_coverage.m4
The previous change seems to have defined LDFLAGS twice rather
than LIBS and LDFLAGS.
=> AX_CODE_COVERAGE: Define CODE_COVERAGE_LIBS

m4/ax_is_release.m4
This is particularly useful in conjunction with git-version-gen,
as provided by gnulib.
Signed-off-by: Simon McVittie <simon.mcvittie@collabora.co.uk>
=> AX_IS_RELEASE: add dash-version policy

m4/ax_compiler_flags_cflags.m4, m4/ax_compiler_flags_cxxflags.m4, m4/ax_compiler_flags_gir.m4, m4/ax_compiler_flags_ldflags.m4
These macros would fail with infinite recursion if used twice for the
same variable, for example
AX_COMPILER_FLAGS_CFLAGS([WARN_CFLAGS], ... some options ...)
AX_COMPILER_FLAGS_CFLAGS([WARN_CFLAGS], ... more options ...)
In particular, invoking AX_COMPILER_FLAGS, followed by
AX_COMPILER_FLAGS_CFLAGS with more "yes" options has this failure mode.
This is because the first time through the macro, we define
ax_warn_cflags_variable = "WARN_CFLAGS" as expected. The second time,
because the first parameter is underquoted, its value is substituted
before calling m4_define, so we inadvertently define
WARN_CFLAGS = "WARN_CFLAGS". The next time WARN_CFLAGS is mentioned,
attempts to expand it will recurse forever, because m4 does not
special-case a macro that appears in its own expansion like cpp …
=> ax_compiler_flags_*: fix underquoting causing infinite recursion

m4/ax_define_sub_path.m4
I noticed this when trying to figure out what this macro is useful for. I have to admit that I still don’t know…? Could you explain what the intended use-case is?
I was hoping it could be used for defining a C preprocessor macro (via `AC_DEFINE`) that contained an expanded ${sysconfdir}, but — even with the necessary bugfixes — the description says the macro will merely replace `${prefix}` with a dotslash.
In the end, I resorted to using:
```m4
AC_DEFINE_UNQUOTED(SYSCONFDIR, "`eval echo $sysconfdir`", [Location of system configuration files])
```
Also, should we consider deleting the macro entirely instead of merging this pull request? As per https://codesearch.debian.net/search?q=AX_DEFINE_SUB_PATH and https://codesearch.debian.net/search?q=AC_DEFINE_SUB_PATH and a quick Google search, …
=> Remove extraneous whitespace to make ifelse() work

m4/ax_enable_builddir.m4
Without AC_CANONICAL_TARGET, I get the following error when running
./configure:
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
mkdir: cannot create directory '': No such file or directory
mkdir: cannot create directory '': No such file or directory
./configure: line 2470: /conftest.tmp: Permission denied
configure: error: could not change to default builddir "./"
With AC_CANONICAL_TARGET (either called explicitly in configure.ac, or
required in AX_ENABLE_BUILDDIR), ./configure works as expected:
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
continue configure in default builddir "./x86_64-unknown-linux-gnu" …
=> ax_enable_builddir: require AC_CANONICAL_TARGET

m4/ax_compiler_flags_ldflags.m4
The linker on macOS does not understand --as-needed, and speaks
--fatal-warnings with a slightly different accent.
=> ax_compiler_flags_ldflags: Fix options for macOS linker

m4/ax_extend_srcdir.m4
This is important for the FreeBSD ports and was submitted by https://github.com/bapt in https://github.com/i3/i3/pull/2551
=> ax_extend_srcdir: also accept absolute paths

m4/ax_gcc_archflag.m4
Update AX_GCC_ARCHFLAG to detect ThunderX (an AArch64 CPU by Cavium) and
set -march/-mcpu accordingly depending on the CPU generation and
compiler support.
=> Add code to detect ThunderX to AX_GCC_ARCHFLAG.

m4/ax_type_socklen_t.m4
The len variable is unused, which causes a compile error resulting in a
failure to detect socklen_t.
Also fix a potential warning about implicit type conversion while
initializing len.
=> AX_TYPE_SOCKLEN_T: fix "-Wall -Werror" compatibility

m4/ax_add_fortify_source.m4
Hi @peti 
This is a new macro to help the ecosystem not add `-D_FORTIFY_SOURCE=2` unconditionally in their `configure.ac`s. The problem is that some distributions have this flag unconditionally enabled in their toolchains, causing unnecessary churn (or even failure with `-Werror`). On the other hand, building with `-D_FORTIFY_SOURCE=2` on is strongly recommended, in order to catch potential security issues.
=> Add new macro AX_ADD_FORTIFY_SOURCE

m4/ax_jni_include_dir.m4
Find the Java directories within the Xcode bundle on macOS 10.8 and
later.
=> Find Java directories on recent macOS versions

m4/ax_check_enable_debug.m4
Since -DNDEBUG is equivalent to "#define NDEBUG 1", explicitly set
the value to ensure that both definitions are equivalent and won't
lead to compiler warnings.
This makes AX_CHECK_ENABLE_DEBUG compatible with AX_CODE_COVERAGE, as
the latter causes -DNDEBUG to be set.
In particular, if AX_COMPILER_FLAGS is also used and thus -Werror
is set (which is the default in that case) this avoids the following
build failure:
./config.h:38:0: error: "NDEBUG" redefined [-Werror]
Submitted in <https://savannah.gnu.org/patch/?9226>
Signed-off-by: Emanuele Aina <emanuele.aina@collabora.com>
=> AX_CHECK_ENABLE_DEBUG: Do not conflict with -DNDEBUG

m4/ax_is_release.m4
Autoconf 2.69 does not set the ${top_srcdir} environment variable in configure scripts any more.
${srcdir} and ${ac_top_srcdir} are both available but the Autoconf manual recommends using ${srcdir}:
From https://www.gnu.org/software/autoconf/manual/autoconf.html#Preset-Output-Variables:
> The preset variables which are available during config.status (see Configuration Actions) may also be used during configure tests. For example, it is permissible to reference ‘$srcdir’ when constructing a list of directories to pass via option -I during a compiler feature check. When used in this manner, coupled with the fact that configure is always run from the top build directory, it is sufficient to use just ‘$srcdir’ instead of ‘$top_srcdir’.
=> AX_IS_RELEASE: use srcdir instead of top_srcdir

m4/ax_gcc_archflag.m4
This patch adds code to detect Cavium ThunderX2 CN99xx (formely Broadcom
Vulcan) to AX_GCC_ARCHFLAG.
=> Add support for Cavium ThunderX2 CN99xx to AX_GCC_ARCHFLAG.

m4/ax_ruby_devel.m4
- Don't use AX_WITH_RUBY which was removed six years ago.
- Use modern Ruby configuration sources.
- Make the version check actually work.
=> Bugfixes for AX_RUBY_DEVEL

m4/ax_compute_relative_paths.m4, m4/ax_recursive_eval.m4
* `AX_RECURSIVE_EVAL` is useful on its own, and consumers
should not be required to pull in the whole of
`AX_COMPUTE_RELATIVE_PATHS` to use it.
=> Move AX_RECURSIVE_EVAL to its own file

m4/ax_ruby_ext.m4
Ruby 2.1 (which Debian Jessie ships) warns about the deprecation:
```
-e:1:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
-e:1:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
/usr/local/lib/site_ruby
```
And newer Ruby versions throw an error:
```
-e:1:in `<main>': uninitialized constant Config (NameError)
```
=> AX_RUBY_EXT: Use RbConfig instead of deprecated Config module

m4/ax_python_devel.m4
The LIBS and SYSLIBS Python configuration variables are lists of
libraries, with typical values (on Debian GNU/Linux) being
LIBS = -lpthread -ldl -lutil
SYSLIBS = -lm
so they should clearly be in a LIBS variable, not LDFLAGS.
Conversely, the LINKFORSHARED Python configuration variable contains
miscellaneous linker options, with its value on Debian being
-Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
so it should be in the LDFLAGS.
This matters when linking statically or using a particularly
pedantic linker: LDFLAGS appear on the linker command-line before
the object files to be linked and (with some linkers) cannot satisfy
undefined symbols, whereas LIBS appear after the object files in
dependency order.
Signed-off-by: Simon McVittie <smcv@debian.org>
=> AX_PYTHON_DEVEL: Swap values of PYTHON_EXTRA_LIBS, PYTHON_EXTRA_LDFLAGS

m4/ax_jni_include_dir.m4
Avoid using AC_CHECK_FILE as it is disabled on cross compilation in some cases.
Original downstream commit addressing this issue: https://github.com/theuni/secp256k1/commit/2d9055f22ca7fd5922059bb3b6ea2ac2540af951
=> AX_JNI_INCLUDE_DIR: Cross-compile fix (avoid AC_CHECK_FILE)

m4/ax_subdirs_configure.m4
This pull request fixes the way empty arguments are handled (i.e nothing is done) in [`AX_SUBDIRS_CONFIGURE`](https://www.gnu.org/software/autoconf-archive/ax_subdirs_configure.html) as opposed to the previous implementation which could set wrong variables when empty arguments were provided.
=> AX_SUBDIRS_CONFIGURE: fix empty argument handling

m4/ax_boost_base.m4
AX_BOOST_BASE first checks if Boost is installed in a standard location
and sets BOOST_CPPFLAGS and BOOST_LDFLAGS accordingly.
If Boost cannot be found, these variables are reset. Further proceedings
depend on whether the actual location was passed in via
`--with-boost=<path>` or not. If it was, BOOST_CPPFLAGS is determined
automatically based on the given path. This automatic detection, however, did
not include BOOST_LDFLAGS.
Consequently, if Boost is in a non-standard location that is given via
`--with-boost`, the user would also have to specify `--with-boost-libdir`.
This commit fixes this issue by also determining BOOST_LDFLAGS
automatically in this particular branch of execution. The performed
check is very similar to the one done in various other locations of the
macro. …
=> AX_BOOST_BASE: Fix missing BOOST_LDFLAGS.

m4/ax_prog_help2man.m4
AX_PROG_HELP2MAN([program list], [man directory prefix], [binary prefix])
`AX_PROG_HELP2MAN` is a macro designed to facilitate usage of [`help2man(1)`](https://www.gnu.org/software/help2man/). It may take three optional arguments:
1. `<program list>`: comma-separated m4 list of input programs.
Specifies the list of input programs which shall be used to produce man pages using [`help2man(1)`](https://www.gnu.org/software/help2man/). If no value is specified, the macro assumes that the sole target will be named `$(PACKAGE_NAME)`. Thus, the two following lines are equivalent:
```
AX_PROG_HELP2MAN
AX_PROG_HELP2MAN([\$(PACKAGE_NAME)])
```
2.  `<man directory prefix>`: directory prefix of the man pages directory.
Sets `AX_HELP2MAN_PREFIX_MANS` to `<man directory prefix>`. Defaults to …
=> AX_PROG_HELP2MAN: new macro

m4/ax_open62541_check_h.m4, m4/ax_open62541_path.m4
* The AX_OPEN62541_CHECK_H macro now uses a slightly different default
list of headers
* The AX_OPEN62541_PATH macro adds another directory to the include
path
=> AX_OPEN62541_*: adapt to v0.2 of open62541

m4/ax_lib_oracle_oci.m4
1. Use C compiler, not C++.
2. Split LDFLAGS into LDFLAGS and LIBS.
However, merge them back to ORACLE_OCI_LDFLAGS afterwards
to preserve interface backward compatibility.
3. Replace C++ style comments with C style.
Resolves mloskot/autotools-modules#2
=> Fix AX_LIB_ORACLE_OCI macro for plain C

m4/ax_compiler_flags_cflags.m4
-Wduplicated-cond since gcc 6
-Wduplicated-branches since gcc 7
-Wlogical-op since gcc 4.3
-Wrestrict since gcc 7
-Wnull-dereference since gcc 6
-Wjump-misses-init since gcc 4.5
-Wdouble-promotion since gcc 4.6
See also https://kristerw.blogspot.de/2017/09/useful-gcc-warning-options-not-enabled.html
=> AX_COMPILER_FLAGS: add new gcc flags

m4/ax_prog_help2man.m4
This pull request fixes the default behaviour of the AX_PROG_HELP2MAN macro
when the input program list is empty. The new implementation correctly
uses the $(PACKAGE_NAME) variable as the default target as opposed to
the previous implementation which produced incorrect make rules.
=> AX_PROG_HELP2MAN: fix default behaviour

m4/ax_boost_base.m4
if host_cpu != [x86_64|ppc64|s390x|sparc64|aarch64|ppc64le] libsubdirs = "",
but it is necessary libsubdirs = "lib"
Invalid execution, superfluous comma.
[qbittorrent issue #7845](https://github.com/qbittorrent/qBittorrent/issues/7845)
=> Fix check for system libraries in both lib64 and lib

m4/ax_prog_date.m4
This macro tries to determine the type of the date (1) command and some of
its non-standard capabilities.
=> Add ax_prog_date.m4

m4/ax_pkg_check_modules.m4
It can make configure.ac files more readable to list the packages on
separate lines. Strip the newlines and extra whitespace with
m4_normalize.
=> AX_PKG_CHECK_MODULES: Normalize whitespace in package lists

m4/ax_gcc_archflag.m4
Update Broadwell patterns in ax_gcc_archflag.m4 to match Intel
documentation. Per "Intel® 64 and IA-32 Architectures Software
Developer’s Manual", Vol. 4, Table 2-1 "CPUID Signature Values of
DisplayFamily_DisplayModel" the following Family/Model combinations are
possible for Broadwell CPUs:
- 06_3DH
- 06_47H
- 06_4FH
- 06_56H
Before this patch only the first combination was recognized, with all
other Broadwell models falling into the `*??6??:*:*:*` case
corresponding to Core 2.
=> AX_GCC_ARCHFLAG: update Broadwell CPUID patterns.

m4/ax_compiler_flags_ldflags.m4
Add -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
but not yet the brand-new textonly, retpolineplt linker flags. Let's wait
what gcc decides on the flags for Spectre, clang went with retpolineplt.
=> ax_compiler_flags_ldflags: harden

m4/ax_compiler_flags_cflags.m4
Several warning flags are incompatible with c++:
-Wnested-externs -Wmissing-prototypes -Wstrict-prototypes -Wdeclaration-after-statement
-Wold-style-definition -Wimplicit-function-declaration -Wjump-misses-init
=> ax_compiler_flags_cflags: c++ fixes

m4/ax_cxx_compile_stdcxx.m4
Now that C++17 has been standardized this warning can be removed.
=> Remove warning about C++17

m4/ax_check_mysql.m4
This pull request is a proposed fix for m4/ax_check_mysql.m4.
The changes fixes two problems I encountered when running the configure script.
The first problem is configure is incorrectly checking for the header path using /usr/include/mysql/mysql_version.h/mysql_version.h as the path.
$ ./configure
...
checking /usr/include/mysql/mysql_version.h/mysql_version.h usability... no
checking /usr/include/mysql/mysql_version.h/mysql_version.h presence... no
checking for /usr/include/mysql/mysql_version.h/mysql_version.h... no
....
After fixing the previous problem, the configure script now encounters an invalid command.
checking if MySQL install supports Plugins... yes
checking if MySQL version is equal or greater than 5.7.21... ./configure: line 4958: 21: command not found
yes
=> fix header file path and version check conditional

m4/ax_lib_hdf5.m4
When iterating over flags from `h5cc`, the `HDF5_{CPPFLAGS,LDFLAGS,LIBS}` variables were assembled in reverse order. This causes problems when linking against static libraries. This patch assembles those variables in the original order.
In master, `HDF5_LIBS` comes out to be: `-lm -ldl -lz -lpthread  -lhdf5 -lhdf5_hl`
With this patch, it comes out to be: `-lhdf5_hl -lhdf5  -lpthread -lz -ldl -lm`
This matches the original order from `h5cc -show`:
```bash
$ h5cc -shlib -show
gcc -fmessage-length=0 -grecord-gcc-switches -O2 -Wall \
-D_FORTIFY_SOURCE=2 -fstack-protector-strong \
-funwind-tables -fasynchronous-unwind-tables \
-fstack-clash-protection -g \
-L/usr/lib64 -lhdf5_hl -lhdf5 -lpthread -lz -ldl -lm -Wl,-rpath -Wl,/usr/lib64
```
I've checked this creates the variables with all of the …
=> AX_LIB_HDF5: fix order of flags

m4/ax_cxx_compile_stdcxx.m4
This is the same thing as in https://savannah.gnu.org/patch/index.php?9572, but I guess patches on github are processed faster. Please let me know which way is preferred.
The problem with the check is that it can't detect whether the version
is with extensions or not. So it can't take the "noext" or "ext"
option into account.
This may be a problem when an extended version of C++ has a feature
that conflicts with another feature from the C++ standard and we have
no way to tell the macro to add a "-std" flag anyway.
An example:
using namespace std::complex_literals;
std::complex<double> c = 1.0;
c += 1.0i;
std::cout << "abs" << c << " = " << abs(c) << '\n';
Here, the "1.0i" constant is either a GCC extension if compiled with
-std=gnu++14 or a standard C++ operator if compiled with …
=> ax_cxx_compile_stdcxx.m4: Drop the check for default C++ version support

bootstrap.sh
We just need some utilities from gnulib, so getting an entire history
of changes of the library is pointless. And it also takes more time.
=> bootstrap.sh: Do a shallow clone of gnulib

m4/ax_cxx_compile_stdcxx.m4
There is a released version of clang that supports C++17, so drop all
the ifdefs that made clang to skip some checks.
Also, a __cplusplus macro is specified to expand to 201703L, so fix
the check accordingly.
=> Some cleanups in C++17 checking code

m4/ax_compiler_flags_cflags.m4
https://github.com/autoconf-archive/autoconf-archive/pull/147 introduced
a regression where, because -Wdeclaration-after-statement etc. are
appended to the compile flags after the user-supplied list of warnings
to disable, it is impossible to disable these warnings.
=> ax_compiler_flags_cflags: fix disabling C-only warnings

m4/ax_check_compile_flag.m4
Replace GPL3 + Autoconf exception by all-permissive license.
See discussion at https://github.com/tesseract-ocr/tesseract/pull/1559.
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> AX_CHECK_COMPILE_FLAG: released under all-permissive license

m4/ax_check_allocated_ctime.m4, m4/ax_check_page_aligned_malloc.m4, m4/ax_check_pathfind.m4, m4/ax_check_posix_regcomp.m4, m4/ax_check_posix_sysinfo.m4, m4/ax_check_strcspn.m4, m4/ax_check_strftime.m4, m4/ax_check_sys_siglist.m4, m4/ax_check_uname_syscall.m4, m4/ax_ext.m4, m4/ax_func_memmove.m4, m4/ax_func_posix_memalign.m4, m4/ax_func_snprintf.m4
Hello,
Autoconf made several macros obsolete including the `AC_TRY_RUN` and in 2000 and since Autoconf 2.50:
http://git.savannah.gnu.org/cgit/autoconf.git/tree/ChangeLog.2
These macros should be replaced with the current `AC_RUN_IFELSE` instead.
This patch was created with the help of the autoupdate script.
Reference docs:
- https://www.gnu.org/software/autoconf/manual/autoconf-2.59/autoconf.pdf
=> Replace obsolete AC_TRY_RUN with AC_RUN_IFELSE

m4/ax_prog_javah.m4
The `AC_TRY_CPP` macro has been made obsolete in Autoconf 2.50 which was released in 2001. It should be replaced with `AC_PREPROC_IFELSE` macro.
Refs:
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/AC_005fACT_005fIFELSE-vs-AC_005fTRY_005fACT.html
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Running-the-Preprocessor.html
=> Replace obsolete AC_TRY_CPP with AC_PREPROC_IFELSE

m4/ax_blas.m4, m4/ax_ext_have_lib.m4, m4/ax_lapack.m4, m4/ax_lib_readline.m4
Autoconf 2.50 introduced new macros in favor of the AC_TRY_FOO. Since Autoconf 2.55 the `AC_TRY_LINK_FUNC` macro has been additionally marked as obsolete and suggested to be replaced with `AC_LINK_IFELSE` and `AC_LANG_CALL`.
Refs:
- http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS
=> Replace obsolete AC_TRY_LINK_FUNCTION macros

m4/ax_afs.m4, m4/ax_include_strcasecmp.m4, m4/ax_ruby_devel.m4, m4/ax_short_sleep.m4, m4/ax_string_strcasecmp.m4, m4/ax_strings_strcasecmp.m4, m4/ax_with_mpatrol.m4, m4/ax_xercesc.m4
Autoconf 2.50 (released in 2001) made several macros obsolete including the `AC_TRY_LINK` which should now be replaced with the `AC_LINK_IFELSE`.
Refs:
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/AC_005fACT_005fIFELSE-vs-AC_005fTRY_005fACT.html
=> Replace obsolete AC_TRY_LINK macros with AC_LINK_IFELSE

m4/ax_append_compile_flags.m4, m4/ax_append_flag.m4, m4/ax_append_link_flags.m4, m4/ax_check_link_flag.m4, m4/ax_check_preproc_flag.m4
There are 5 files with an authorship to @mkbosmans in the autoconf-archive that come from a single commit in 2011. 
git show --summary cfea4ee52f7f2490937976b828a3b82d07b431f2
Author: Maarten Bosmans <mkbosmans@gmail.com>
Date:   Sat Jul 2 12:06:31 2011 +0200
ax_append_flag: Split file into one macro per file
create mode 100644 m4/ax_append_compile_flags.m4
create mode 100644 m4/ax_append_flag.m4
create mode 100644 m4/ax_append_link_flags.m4
create mode 100644 m4/ax_check_compile_flag.m4
delete mode 100644 m4/ax_check_flag.m4
create mode 100644 m4/ax_check_link_flag.m4
create mode 100644 m4/ax_check_preproc_flag.m4
I would like to relicense my own stuff to all-permissive. We had some questions about licensing issues from other projects lately, and an easier license makes it easier for …
=> all-permissive for macros from Guido Draheim / Maarten Bosmans

m4/ax_cxx_have_complex_math1.m4, m4/ax_cxx_have_complex_math2.m4, m4/ax_cxx_have_ieee_math.m4, m4/ax_cxx_have_system_v_math.m4
Autoconf 2.50 in 2001 made several macros obsolete. These include macros for temporary changing the language - `AC_LANG_SAVE`, `AC_LANG_CPLUSPLUS`, and `AC_LANG_RESTORE`. Instead of these the `AC_LANG_PUSH` and `AC_LANG_POP` macros should be used with later Autoconf versions.
`AC_TRY_LINK` macros should be replaced with `AC_LINK_IFELSE` and `AC_LANG_PROGRAM`.
Refs:
- http://git.savannah.gnu.org/cgit/autoconf.git/tree/NEWS
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Language-Choice.html
=> Replace AC_TRY_LINK and AC_LANG_

m4/ax_c_declare_block.m4, m4/ax_c_long_long.m4, m4/ax_c_var_func.m4, m4/ax_cflags_no_writable_strings.m4, m4/ax_cflags_strict_prototypes.m4, m4/ax_check_typedef.m4, m4/ax_compile_check_sizeof.m4, m4/ax_create_stdint_h.m4, m4/ax_cxx_have_koenig_lookup.m4, m4/ax_decl_wchar_max.m4, m4/ax_func_mkdir.m4, m4/ax_gcc_const_call.m4, m4/ax_gcc_malloc_call.m4, m4/ax_gcc_warn_unused_result.m4, m4/ax_struct_semun.m4, m4/ax_sysv_ipc.m4, m4/ax_type_socklen_t.m4
Autoconf made several macros obsolete including the `AC_TRY_COMPILE` in 2000 and since Autoconf 2.50:
http://git.savannah.gnu.org/cgit/autoconf.git/tree/ChangeLog.2
These macros should be replaced with the current `AC_COMPILE_IFELSE` instead.
This patch was created with the help of autoupdate script.
Refs:
- https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/AC_005fACT_005fIFELSE-vs-AC_005fTRY_005fACT.html
=> Replace obsolete AC_TRY_COMPILE with AC_COMPILE_IFELSE

m4/ax_prog_doxygen.m4
Show the actual unsatisfied dependency instead of repeating the currently tested feature.
This corrects messages such as `doxygen-html requires doxygen-html` to the intended `doxygen-html requires doxygen-doc`.
=> Fix doxygen error message

m4/ax_lib_gdal.m4, m4/ax_lib_libkml.m4
Autoconf made several macros obsolete including `AC_HELP_STRING` somewhere in 2003 in Autoconf 2.59 version. Macro should be replaced with `AS_HELP_STRING`.
=> Replace obsolete AC_HELP_STRING with AS_HELP_STRING

m4/ax_code_coverage.m4
The local Automake distclean target is distclean-local, not
dist-clean-local.  Update the AX_CODE_COVERAGE macro documentation,
accordingly.
=> Fix AX_CODE_COVERAGE 'distclean' related comments

m4/ax_check_enable_debug.m4
Reintroduce change (6e6c447) that addressed NDEBUG redefinition when
using both the AX_CODE_COVERAGE and AX_CHECK_ENABLE_DEBUG macros.  It
was lost in the previous patch to ax_check_enable_debug.m4 (d049eeb).
=> ax_check_enable_debug: Correct NDEBUG regression.

m4/ax_check_gnu_make.m4
The addition of support for ifnGNUmake introduced a bug that made
ifGNUmake be set to "#" in the case GNU Make is detected.
Signed-off-by: Ignacy Gawędzki <ignacy.gawedzki@green-communications.fr>
=> ax_check_gnu_make: Fix setting of ifGNUmake and ifnGNUmake.

m4/ax_code_coverage.m4
Consider the following minimal example:
**`configure.ac`**
```
AC_INIT([package], [version])
AM_INIT_AUTOMAKE([foreign])
AC_CONFIG_FILES([Makefile])
AX_CODE_COVERAGE
AC_OUTPUT
```
**`Makefile.am`**
```
include $(top_srcdir)/aminclude_static.am
clean-local: code-coverage-clean
distclean-local: code-coverage-dist-clean
```
When using `make distcheck` with `--enable-code-coverage`, it fails with the following error:
```
$ autoreconf --install
[...]
$ ./configure --enable-code-coverage
[...]
$ make distcheck
[...]
Makefile:241: *** Recursive variable 'AM_DISTCHECK_CONFIGURE_FLAGS' references itself (eventually).  Stop.
```
This can be fixed by using a simply-expanded variable instead, as described in the [`make` documentation](https://www.gnu.org/software/make/manual/html_node/Error-Messages.h …
=> ax_code_coverage: fix self-referencing variable error in distcheck

m4/ax_is_release.m4
Detect [git worktrees ](https://git-scm.com/docs/git-worktree)in the `git-directory` case.  Git worktrees contain a `.git` file rather than a directory.
=> ax_is_release: Support git worktrees.

m4/ax_have_qt.m4
Under Windows, the generated Makefile does not contain the required
information by default, because it is contained in other Makefiles
for the Release and Debug build variants. It is therefore necessary
to use only one build variant.
This issue has been detected on cross compiling gwenhywfar.
=> ax_have_qt.m4: Fix not getting variables from the generated Makefile on Windows

m4/ax_have_qt.m4
Makefile generated by qmake include paths relative to the build
directory that is assumed to be current.
=> ax_have_qt: workaround qmake bug when building out of tree

m4/ax_cc_maxopt.m4
AX_CC_MAXOPT checks whether CFLAGS was set by the user; if so, the user’s
setting is respected. This behavior is retained, of course.
However, AX_CC_MAXOPT was then setting CFLAGS="". This overrode the default
setting by configure, which usually includes -g. Hence, if CFLAGS was not
set by the user, retain the default setting, to preserve the ability to
debug.
A typical default setting from configure is "-g -O2". This means that
AX_CC_MAXOPT might typically set CFLAGS to "-g -O2 -O3". This is fine,
because the later -O3 will override the earlier -O2. (The only assumption is
that all compilers that AX_CC_MAXOPT knows behave in this sane way.)
=> ax_cc_maxopt.m4: retain setting of CFLAGS by configure

m4/ax_boost_base.m4
Currently there're 3 well-known ABIs in use on MIPS64 systems, with
the respective libdir as follows:
* n64: `lib64`,
* n32: `lib32`,
* o32: `lib`.
Probe all three of them.
=> ax_boost_base: fix libsubdirs preference for MIPS64

m4/ax_boost_base.m4
Fixes an oversight in #192.
Sorry for the noise!
=> ax_boost_base: fix incomplete coverage of MIPS64 systems

m4/ax_blas.m4, m4/ax_lapack.m4
The `ax_blas` and `ax_lapack` macros use `case $with_blas` and `case $with_lapack` statements to check for a number of library suffixes via globs. Prior to this PR, these suffixes did not include the globs `*.dylib` and `*.dylib.*`, both of which check for macOS suffixes used to denote shared libraries. This PR adds globs corresponding to these macOS shared library suffixes.
=> ax_{blas,lapack}: add macOS dynamic library suffix (`.dylib`) globs to `with_{blas,lapack}` case statements  

m4/ax_check_openssl.m4
This PR originates from https://github.com/python/cpython/pull/15556, where it was suggested to bring it up here.
I was in a situation where I have many install of OpenSSL in many environments, and not all of my install of OpenSSL will be compatible for what I try to do. If we can improve the message with narrower scope of what it is looking, it would help narrowing down my hunt.
Please let me know if anything can be improved on this PR!
=> Improve message for openssl lookup

m4/ax_r_package.m4
If a package exists, the test for its existence produces an error with `_R_CHECK_LENGTH_1_CONDITION_=true` (introduced in R 3.4.0), e.g.
```sh
$ _R_CHECK_LENGTH_1_CONDITION_=true R --silent --vanilla -e 'if(is.na(packageDescription("BH"))) stop("not found")'
> if(is.na(packageDescription("BH"))) stop("not found")
Error in if (is.na(packageDescription("BH"))) stop("not found") :
the condition has length > 1
Execution halted
```
This is because `is.na(packageDescription("BH"))` resolved to a logical vector of 15(!) `FALSE` values when package 'BH' is installed.  If it is not installed, then it resolves to `TRUE`.
=> BUG FIX: ax_r_package: Fixing a _R_CHECK_LENGTH_1_CONDITION_=true bug

m4/ax_boost_asio.m4, m4/ax_boost_chrono.m4, m4/ax_boost_context.m4, m4/ax_boost_coroutine.m4, m4/ax_boost_date_time.m4, m4/ax_boost_filesystem.m4, m4/ax_boost_iostreams.m4, m4/ax_boost_locale.m4, m4/ax_boost_log.m4, m4/ax_boost_log_setup.m4, m4/ax_boost_program_options.m4, m4/ax_boost_serialization.m4, m4/ax_boost_signals.m4, m4/ax_boost_system.m4, m4/ax_boost_test_exec_monitor.m4, m4/ax_boost_thread.m4, m4/ax_boost_unit_test_framework.m4, m4/ax_boost_wave.m4, m4/ax_boost_wserialization.m4
When testing for Boost libraries, return the library that could not be found. 
Currently the [Boost::Regex](https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_boost_regex.m4) m4 is the only macro that mentions the library name when it fails.
=> Improve Boost library error messages

m4/ax_pthread.m4
With gcc's warning -Wunused-but-set-parameter enabled (which is enabled
with -Wextra) and -Werror, configuring with the AX_PTHREAD macro fails
with:
configure:6783: checking whether pthreads work with -pthread
configure:6877: ccache gcc -o conftest -g3 -O0 -Werror -Wall -Wextra  -fmax-errors=1 -fdiagnostics-color=always -Wall -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_22 -pthread   conftest.c   >&5
conftest.c: In function 'routine':
conftest.c:37:51: error: parameter 'a' set but not used [-Werror=unused-but-set-parameter]
static void routine(void *a) { a = 0; }
^
cc1: all warnings being treated as errors
Change the code to make it use, not only set, the parameter.
=> ax_pthread.m4: avoid unused-but-set-parameter warning

m4/ax_gcc_func_attribute.m4
newer gcc warns about function might be a candidate for
gnu_printf format attribute [-Wsuggest-attribute=format]
Usage: AX_GCC_FUNC_ATTRIBUTE(gnu_format)
and:
#ifdef HAVE_FUNC_ATTRIBUTE_GNUFORMAT
\__attribute__ ((format (gnu_printf, 1, 2)))
#elif HAVE_FUNC_ATTRIBUTE_FORMAT
\__attribute__ ((format (printf, 1, 2)))
#endif
=> add AX_GCC_FUNC_ATTRIBUTE(gnu_format)

m4/ax_boost_process.m4
I missed this in #202: `want_boost` is ambiguous, so this PR sets `want_boost_process` based on `--with-boost-process`
=> Use want_boost_process instead of want_boost

m4/ax_boost_thread.m4
The android libc, bionic, provides built-in support for pthreads, so no additional linking is necessary.
Setting `-pthread` [breaks the build](https://github.com/protocolbuffers/protobuf/issues/1373).
=> ax_boost_thread: do not set -pthread on Android

m4/ax_have_epoll.m4
When building with -Werror -Wunused-but-set-variable, the code snippets
in this file generate a warning, causing the test to spuriously fail.
Remove the "rc" variables, since they're not used.
Sample config.log output:
configure:22489: checking for Linux epoll(7) interface
configure:22515: ccache gcc -o conftest -g3 -O0 -Wall -Werror -Wextra -Wno-type-limits -Wno-missing-declarations -Wno-missing-field-initializers -Wno-si      gn-compare -Wno-implicit-fallthrough -Wno-unused-parameter -I/home/smarchi/install/include -DHAVE_LINUX_VERSION_H -L/home/smarchi/install/lib conftest.c       -lurcu-cds  >&5
conftest.c: In function 'main':
conftest.c:184:9: error: variable 'rc' set but not used [-Werror=unused-but-set-variable]
int fd, rc;
^~
cc1: all warnings being treated as errors
=> ax_have_epoll: avoid -Wunused-but-set-variable errors

m4/ax_add_fortify_source.m4
gcc-9 warns when -O is not enabled.
Add linker step for broken msys2 packages.
=> ax_add_fortify_source.m4: improve for -Wcpp

m4/ax_pthread.m4
This fix was created to fix a linking issue for fplll (https://github.com/fplll/fplll/issues/395).
I'm hoping this could be of interest for autoconf-archive.
Note that for GCC and Clang -pthread generally implies -lpthread,
except when -nostdlib is passed.
This is problematic using libtool to build C++ shared libraries with pthread:
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25460
[2] https://bugzilla.redhat.com/show_bug.cgi?id=661333
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=468555
To solve this, first try -pthread together with -lpthread for GCC and Clang.
Changes:
- added support for combination "cflags,ldflags" style option to try
- check for Clang early
- for GCC and Clang try "-pthread,-lpthread" first, followed by original options (-pthread, etc.)
- Perform check …
=> Fix ax_pthread.m4: try to include -lpthread in PTHREAD_LIBS for GCC & Clang since automatic usage is not guaranteed

m4/ax_prog_cc_for_build.m4
This series of commits fixes bugs of `AX_PROG_CC_FOR_BUILD`.  Here simple test files:
`bootstrap.sh`:
~~~sh
#! /usr/bin/sh
m4_localdir=../../m4
mkdir -p build-aux
echo "ACLOCAL_FLAGS = -I $m4_localdir" > Makefile.am
autoreconf -vfi .
~~~
`configure.ac`:
~~~m4
AC_INIT(cc_for_build,0,myemail@org.com)
AC_CONFIG_AUX_DIR([build-aux])
AM_INIT_AUTOMAKE([foreign])
AC_CONFIG_FILES([Makefile])
AX_PROG_CC_FOR_BUILD
AC_OUTPUT
echo "
CC                               $CC
CC_FOR_BUILD            $CC_FOR_BUILD
CFLAGS_FOR_BUILD    $CFLAGS_FOR_BUILD
CPPFLAGS_FOR_BUILD  $CPPFLAGS_FOR_BUILD
LDFLAGS_FOR_BUILD   $LDFLAGS_FOR_BUILD
BUILD_EXEEXT              $BUILD_EXEEXT
BUILD_OBJEXT             $BUILD_OBJEXT
"
~~~
Additionally, happy to do the following if you devs consider it appropriate:
* add `AC_ARG_VAR` …
=> ax_prog_cc_for_build.m4: bug fixes

m4/ax_gcc_func_attribute.m4
GCC outputs a warning when Wstrict-prototypes is on, in such case the
attribute detection always fails even if the attribute is actually
supported. This change checks for the "-Wattributes" warning in
conftest.err instead of the existence of the file.
=> ax_gcc_func_attribute: Revise the detection of unknown attributes

m4/ax_boost_base.m4
Without this patch, building on an RPI4 ends up with
BOOST_LDFLAGS=-L/usr/lib while libs are actually under
/usr/lib/arm-linux-gnueabihf, and configure will later file during
AX_BOOST_THREAD macro.
=> m4/ax_boost_base.m4: Fix debian multiarch_libsubdir path for arch armv7l

m4/ax_cxx_compile_stdcxx.m4
Commit bbb60ca79952c20ee0b187208533d98206b156d1 removed this check because
it can't support the user requesting noext.  But if the user didn't specify
ext or noext, using the default mode should be fine.  So this patch restores
the check if the second argument is empty.
=> ax_cxx_compile_stdcxx.m4: Restore check for default C++ version support

m4/ax_gcc_func_attribute.m4
The test for the fallthrough attribute fails due to other compiler
warnings when using clang.  The following warnings are generated:
warning: no case matching constant switch condition '0'
warning: control reaches end of non-void function [-Wreturn-type]
Because of these additional warnings, the test always results in a
failure for the fallthrough attribute.
Update ax_gcc_func_attribute.m4 to eliminate the warnings that are
masking the test for the fallthrough attribute.
Note, tested the entire suite of attribute tests using clang and only
the fallthrough test contained warnings that were not related to the
the attribute being tested.
=> ax_gcc_func_attribute.m4: test fails for the fallthrough attribute with clang

m4/ax_boost_base.m4
Hi!
This PR adds a proper E2K architecture[1] support in the AX_BOOST_BASE.
[1] https://en.wikipedia.org/wiki/Elbrus-8S
=> AX_BOOST_BASE: add e2k to the list of lib64 architectures

m4/ax_pthread.m4
This reverts commit 2567e0ce0f3a11b535c6b527386197fb49ff172b.
* `AC_CANONICAL_HOST` is the system on which the actual binary will run,
`AC_CANONICAL_TARGET` is the system for which code is generated. The
Autoconf manual even mentions that
`--target=target-type`
the type of system for which any compiler tools in the package produce code (**rarely needed**).
=> Revert "AX_PTHREAD: target > host"

m4/ax_python_devel.m4
Python distutils module would be deprecated, it already prints warnings. Support obtaining requested information from sysconfig python module, which is its replacement.
Adds also small addition to export also platform dependent site-packages path.
=> Python devel update to sysconfig

m4/ax_ms_cpprest.m4
Needed to add a [few libraries](https://github.com/Microsoft/cpprestsdk/issues/457#issuecomment-305037216) that weren't already supported by the archive in toying with *Microsoft's C++ Rest SDK*.
This particular macro provides support for the [Microsoft C++ Rest SDK](https://github.com/Microsoft/cpprestsdk/wiki/Getting-Started-Tutorial) itself.
**Example**
AX_MS_CPPREST([2.10], [], [AC_MSG_ERROR([You need the Microsoft C++ Rest SDK library])])
Pull requests #229 and #230 are related too, and target the 2 specific Boost libraries that aren't already supported needed in order to enable the Autoconf nerfstick for programs utilizing Microsoft's C++ Rest SDK.
=> Add support for Microsoft's C++ Rest SDK

m4/ax_boost_atomic.m4
Needed to add a couple libraries from boost that weren't already supported by the archive in toying with Microsoft's C++ Rest SDK.
This particular macro provides support for Boost::Atomic
Example
AX_BOOST_ATOMIC([1.7], [], [AC_MSG_ERROR([You need the Boost::Atomic library])])
=> Add Boost::Atomic support to AX_BOOST_<X>

m4/ax_boost_random.m4
Needed to add a couple libraries from boost that weren't already supported by the archive in toying with Microsoft's C++ Rest SDK.
This particular macro provides support for Boost::Random
Example
AX_BOOST_RANDOM([1.7], [], [AC_MSG_ERROR([You need the Boost::Random library])])
=>  Add Boost::Random support to AX_BOOST_<X>

m4/ax_pkg_swig.m4
- when SWIG is found but no minimal version is required,
execute action-if-found
- when only a partial version is given as minimal version,
correctly set minor and/or patch to 0 if missing
Without the fix, AX_PKG_SWIG([4]) is the same as AX_PKG_SWIG([4.4.4])
=> AX_PKG_SWIG: fix version checking

m4/ax_check_sign.m4
This changes the obsolete AC_TRY_COMPILE to the newer
AC_COMPILE_PROGRAM.
=> Modernize ax_check_sign.

m4/ax_prog_cc_for_build.m4
The second commit fixes
https://savannah.gnu.org/patch/?9926
=> AX_PROG_CC_FOR_BUILD fixes

NEWS, m4/ax_cc_for_build.m4
The AX_PROG_CC_FOR_BUILD has seen a lot more updates than
AX_CC_FOR_BUILD, and is generally way more complete.  The latter
hardcoded `gcc` as the native compiler fallback and lacks any of
the standard $build- prefix searches.
It also uses non-standard cache vars -- it's using the bfd_cv_xxx
namespace instead of the ax_cv_xxx namespace everything else does.
Otherwise, the macros largely have the same intention: to find a
compiler for the build system, and setup the exe extension.  So
deprecate AX_CC_FOR_BUILD and have it redirect automatically.
=> AX_CC_FOR_BUILD: deprecate in favor of AX_PROG_CC_FOR_BUILD

m4/ax_pthread.m4
This silences the deprecation warning emitted for $as_echo by the
upcoming 2.70 version of Autoconf.
=> ax_pthread.m4: replace deprecated $as_echo with AS_ECHO()

m4/ax_cc_maxopt.m4
Missing ;; in the ax_cv_c_compiler_vendor case statement causing syntax error with libffi configure:
```
line y: syntax error near unexpected token `)'
line y: `    gnu)'
```
Error was identified building libffi:
- https://github.com/libffi/libffi/issues/692
Raised as savannah patch:
- https://savannah.gnu.org/patch/index.php?10186
=> AX_CC_MAXOPT: Fix nvhpc case

m4/ax_python_devel.m4
Adds a shim Python class so the backward-compatible version-comparison strings can be used, but the comparisons actually decompose the version tuples. Needed to get functioning Python-version checks between < .10 and >= .10 version-part numbers.
=> Fix Python version-string comparisons in ax_devel_python.m4

m4/ax_prog_cc_for_build.m4
The ac_cv_c_compiler_gnu wasn't properly restored to original
state (f.e. yes), but value of the "save" variable was used:
ac_cv_c_compiler_gnu=${ac_cv_c_compiler_gnu=saved_ac_cv_c_compiler_gnu}
Additionally, we don't need to cache the saved_ac_cv_c_compiler_gnu
and was_set_ac_cv_c_compiler_gnu, so remove the ac_cv_ from their names.
This would not manifest on a single run, but any repeated run with cache
file (./configure -C) would be broken.
=> ax_prog_cc_for_build: Properly restore ac_cv_c_compiler_gnu

m4/ax_lib_netcdf4.m4
nf-config may not be installed under the same directory as nc-config.
To avoid the automatic definition of nf-config, setting of NF_CONFIG
variable is introduced for a workaround.
=> ax_lib_netcdf4: enable NF_CONFIG run-time definition.

m4/ax_cxx_compile_stdcxx.m4
MSVC always sets __cplusplus to 199711L in older versions; newer versions
do the same unless /Zc:__cplusplus is specified as well as a `/std:c++<NN>`
switch:
https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/
This fixes a regression compared to the old separate
AX_CXX_COMPILE_STDCXX_11, etc macros which didn't check the value of
__cplusplus so worked OK with MSVC.
=> ax_cxx_compile_stdcxx: Fix for MSVC

m4/ax_boost_json.m4
Add AX_BOOST_JSON() to search for Boost::JSON
(which is in boost 1.75 or newer)
Macro derived from AX_BOOST_RANDOM().
=> ax_boost_json: implement for Boost::JSON library

m4/ax_boost_base.m4
Users with Boost installed via homebrew on arm64 (M1) hardware will
have the libs under this path. Not sure if this is something you'd want
to accomodate, but we currently patch this into the macro, so have
decided to upstream.
=> boost_base: add /opt/homebrew to search paths

m4/ax_add_fortify_source.m4, m4/ax_c99_inline.m4, m4/ax_c_var_func.m4, m4/ax_check_posix_regcomp.m4, m4/ax_check_posix_sysinfo.m4, m4/ax_check_strftime.m4, m4/ax_check_uname_syscall.m4, m4/ax_cpu_freq.m4, m4/ax_func_memmove.m4, m4/ax_func_snprintf.m4
Clang 16 makes -Wimplicit-function-declaration an error by default.
Signed-off-by: Sam James <sam@gentoo.org>
=> Clang 16 fixes

m4/ax_cxx_compile_stdcxx.m4
MSVC defaults to C++14 and needs -std:c++NN to enable support for newer versions so add that to the list of options to try.
=> AX_CXX_COMPILE_STDCXX: Fix MSVC with C++17 or later

m4/ax_c_restrict.m4
to check for broken gcc-5 and clang-6 implementations
resubmit with proper name (opposed to ax_cc_restrict)
=> Add ax_c_restrict

m4/ax_pkg_swig.m4
mingw64 swig -swiglib prints a newline after each lib,
there are two:
SWIG_LIB = C:\msys64\MINGW64\bin\Lib
C:/msys64/MINGW64/share/swig/3.0.12
* m4/ax_pkg_swig.m4: strip \r\n in SWIG_LIB
=> fix SWIG_LIB windows newline

m4/ax_check_sign.m4
Prevents accidents if -Werror happens to be enabled.
=> ax_check_sign: Avoid an unused warning

m4/ax_python_devel.m4
The faulty code was introduce in commit df89f6cdaade38f3c1c9987be0c5a57c96fc1730 https://github.com/autoconf-archive/autoconf-archive/commit/df89f6cdaade38f3c1c9987be0c5a57c96fc1730
The current code tuple(sys.version_info) gives the 5-tuple (3, 10, 7, 'final', 0) while the former code sys.version.split()[0] would give the 3-tuple (3, 10, 7). So, at first glance, the current code tuple(sys.version_info) should be replaced by tuple(sys.version_info)[:3].
A patch that applied to the current ax_python_devel serial 32 is attached.
=> Fix ax_python_devel serial 32 fails with current python3

m4/ax_have_qt.m4
Since a long time I'm seeing this when running AX_HAVE_QT :
> checking for Qt... Info: creating stash file /tmp/tmp.2FXDo4jy40/.qmake.stash
> rmdir: failed to remove '/tmp/tmp.2FXDo4jy40': Directory not empty
> $ ls -a /tmp/tmp.2FXDo4jy40/
> .  ..  .qmake.stash
=> AX_HAVE_QT: remove qmake stash file before rmdir

m4/ax_have_qt.m4
The AX_HAVE_QT macro uses an uninitialized shell variable am_have_qt_qmexe. Fix it.
=> Fix  AX_HAVE_QT

m4/ax_lib_netcdf4.m4
NF_CONFIG is better and safer than NC_CONFIG, for NETCDF4_FFLAGS and NETCDF4_FLIBS configuration.
=> ax_lib_netcdf4: NF_CONFIG instead of NC_CONFIG for Fortran flags.

m4/ax_boost_base.m4, m4/ax_cc_attrcommon.m4, m4/ax_cc_tentdef.m4, m4/ax_check_java_plugin.m4, m4/ax_cvs.m4, m4/ax_ext_have_lib.m4, m4/ax_ms_cpprest.m4, m4/ax_path_bdb.m4, m4/ax_pkg_mico.m4, m4/ax_python_config_var.m4
A typo checker in our project caught some typos in some macros.  Fixed those and few others that were found.
=> Fix various typos

m4/ax_add_fortify_source.m4
it didnt error anymore, just warned.
thus without -O it still enabled the 2nd variant
=> ax_add_fortify_source.m4: fix 2nd probe

m4/ax_prototype.m4
The `unused-variable` warning must be explicitly disabled to prevent accidental failures when the user has e.g. enabled `-Wall` (which enables `unused-variable`), since the macro uses `-Werror` to check the result.
Without disabling the warning, all prototype tests will fail with GCC because the code creates a variable to check the function type and then doesn't use it. This results in what looks like no prototypes matched while in fact one could match, but was rejected due to implicit or explicit `-Wunused-variable` together with `-Werror` (in other words, was rejected, but not by the warning/error that was meant to be used by the macro as the main criterion).
Tested, works for me.
=> ax_prototype: Disable "unused variable" warning

m4/ax_add_fortify_source.m4, m4/ax_c_declare_block.m4, m4/ax_c_restrict.m4, m4/ax_cc_tentdef.m4, m4/ax_check_define.m4, m4/ax_check_page_aligned_malloc.m4, m4/ax_check_strftime.m4, m4/ax_check_sys_siglist.m4, m4/ax_cpu_freq.m4, m4/ax_ext.m4, m4/ax_func_posix_memalign.m4, m4/ax_have_select.m4, m4/ax_openmp.m4, m4/ax_sys_weak_alias.m4
* With Clang having switched to modern C conventions already and GCC following suit soon, we want to have macros that work in the presence of `-Wstrict-prototypes` in all C language modes, not just C23.
=> Make macros `-Wstrict-prototypes` compatible

m4/ax_lua.m4
Since the current Lua version is 5.4, many distros package it with a bare `lua` binary and suffix older builds with the version number. This is *not* universally true however, nor is it forward-compatible. On systems where there is either no default Lua or the default Lua is set to an older version, searching for the binary with the version suffix is the only way to find the newest one. This should be done in priority to falling back to older versions for consistency.
=> Add Lua 5.4 support to AX_PROG_LUA macro

m4/ax_python_devel.m4
The test should check the variable, not the fixed string. Most probably a simple typo, so fix it.
=> ax_python_devel: fix typo preventing correct variable evaluation

m4/ax_gcc_builtin.m4
The AS_VAR_IF check can be a simpler alternative to testing for variable value inside AS_IF.
=> Use AS_VAR_IF in ax_gcc_builtin.m4

m4/ax_boost_base.m4
Previously BOOST_CPPFLAGS was set to a nonsensical -I/include/boost-0 value if Boost headers were not found at all and BOOST_LDFLAGS was similarly set to a wrong (although less obviously so) value in this case because they kept the last values tested by the macro.
Just don't set these variables at all if detecting Boost failed.
=> AX_BOOST_BASE: Don't set BOOST_*FLAGS if Boost is not found

m4/ax_check_compile_flag.m4
Seemingly that at some point clang started accepting _any_ flags, whereas previously it would error out.
These days, you can give it -Whamsandwich and it will succeed, while at the same time throwing an annoying warning.
Add -Werror so that everything gets flagged and set accordingly.
Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=108082
Cc: Vinson Lee <vlee@freedesktop.org>
Repored-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Dylan Baker <dylan@pnwbakers.com>
Reviewed-by: Eric Engestrom <eric.engestrom@intel.com>
=> ax_check_compile_flag: add -Werror when checking for compiler flags

m4/ax_cxx_compile_stdcxx.m4
There are three changes here, each as a separate commit.  They are related so it seemed simplest to just open one PR for them, but if you'd prefer I can open a series of PRs.
With these changes we seem to correctly probe C++17, C++20 and C++23 support with various versions of GCC, clang and MSVC.
=> AX_CXX_COMPILE_STDCXX changes

m4/ax_code_coverage.m4
The lcov >= 2.0 refactored error handling and by default it fails when an unused remove pattern is provided:
LCOV   --remove /tmp/* */tests/*.c
lcov: ERROR: 'exclude' pattern '/tmp/*' is unused.
(use "lcov --ignore-errors unused ..." to bypass this error)
Based on the macro history is is not clear why the /tmp/* would be needed by default. Usual autotools projects don't use /tmp/. If needed users can still add this pattern to
CODE_COVERAGE_IGNORE_PATTERN.
This can be reproduced for example in Fedora 40 which comes with lcov 2.0:
```
docker run --rm -it fedora:40                                                  
dnf install -y gcc automake autoconf gawk lcov gcovr git autoconf-archive      
git clone https://github.com/janzizazizka/autotools-template.git               
cd …
```
=> ax_code_coverage: remove /tmp/* from remove patterns failing with lcov 2.0

doc/autoconf-archive.texi, m4/ax_check_glu.m4, m4/ax_cpu_freq.m4, m4/ax_dist_msi.m4, m4/ax_lua.m4, m4/ax_prog_cc_for_build.m4, m4/ax_prog_cxx_for_build.m4, m4/ax_prog_tcl.m4, m4/ax_sys_perlsharpbang.m4, m4/ax_try_awk_anyout.m4, m4/ax_try_awk_expout.m4
* Both `re-usable` and `reusable` can be seen as correct, but:
* Majors dictionaries suggest `reuse` only:
* [OED](https://www.oed.com/search/dictionary/?q=re-use)
* [Cambridge](https://www.oxfordlearnersdictionaries.com/definition/english/reuse_1)
* [Collins](https://www.collinsdictionary.com/dictionary/english/reuse)
* [Longman](https://www.ldoceonline.com/dictionary/reuse)
* [Merriam-Webster](https://www.merriam-webster.com/dictionary/reuse)
* [Oxford Learner's Dictionary](https://dictionary.cambridge.org/dictionary/english/reuse)
* From [The Blue Book of Grammar and Punctuation](https://www.grammarbook.com/blog/hyphens/hyphens-with-the-prefix-re/):
> Use the hyphen with the prefix _re_ only when _re_ means _again_ AND omitting the hyphen would cause confusion with another word.
* Both …
=> Fix typos found by codespell

m4/ax_cxx_compile_stdcxx.m4
m4_if had an extra [] in the params
m4_define was not define-ing without [...] around the source to be concat'd
unsure if the m4_if extra param was a holdover, or if ext|noext was not used frequently enough to be noticed
unsure if prior m4_define dealt with source not between [...] but this seems to resolve the issue
=> m4_define with braces around concat source, m4_if without extra arg

m4/ax_lua.m4
This is a follow up to #287.
This is a much bigger change adding support for LuaJIT as a Lua interpreter. This is a tricky addition because two sets of version numbers are involved: the Lua VM version (which for LuaJIT is *lower* that current PUC Lua releases, 5.1 vs 5.4) and also a JIT version. It is also quite common to have both PUC Lua and LuaJIT variants installed on a system, but the lower numbering scheme does not mean that PUC should be preferred.
This implementation leaves it up to the user to specifically request LuaJIT be considered by adding a `--with-luajit` configure option. If they do that and it is set to true, then the regular Lua macros will function in the usual way but with the binary names, include paths, and other things tweaked for use with LuaJIT.
I've been using …
=> Add LuaJIT support to AX_PROG_LUA macro

m4/ax_check_java_plugin.m4
I may be missing something, but `zipinf` is used everywhere else, so `ziping` looks like an error.
=> Typo: ziping → zipinf

m4/ax_cxx_compile_stdcxx.m4
This commit breaks AX_CXX_COMPILE_STDCXX noext/ext option handling, which caused
"AX_CXX_COMPILE_STDCXX(20, [noext], [optional])"
to result in
"checking whether g++ supports C++20 features with -std=gnu++20... yes"
which is not the desired outcome when using "noext". It should check for "-std=c++20" instead for "-std=gnu++20", as it did before.
See
<https://github.com/autoconf-archive/autoconf-archive/pull/300#issuecomment-2416443298> and
<https://github.com/autoconf-archive/autoconf-archive/commit/5b0d43b767bf3f800f97892905b6d1ba50150f1a#commitcomment-147999469> .
=> Revert broken part of commit 5b0d43b767bf3f800f97892905b6d1ba50150f1a

m4/ax_prog_cc_for_build.m4
This pull request is a mirror of [patch #10452](https://savannah.gnu.org/patch/index.php?10452).
The BUILD_EXEEXT and BUILD_OBJEXT variables in AX_PROG_CC_FOR_BUILD are broken again in Autoconf 2.70 and later.
This patchset fixes compatibility problems found in Autoconf 2.70 and later.
* Make `BUILD_EXEEXT` and `BUILD_OBJEXT` work again.
* Tweak the previous workaround of `ac_cv_c_compiler_gnu` code and make the solution permanent. The users should now be able to override the `ac_cv_build_c_compiler_gnu` cache variable.
* Fix regression where the `ac_cv_prog_cc_c99` and `ac_cv_prog_cc_c11` macros
are not popped after the `AX_PROG_CC_FOR_BUILD` call.
* Support `ac_build_prog_cc_stdc` (Autoconf 2.70) and `ac_cv_build_prog_cc_c23` (Autoconf 2.73).
=> AX_PROG_CC_FOR_BUILD patches that fix BUILD_{EXE,OBJ}EXT (Autoconf 2.70)

m4/ax_cpu_freq.m4
Cache variables must contain `_cv_` to be cached otherwise this warning is emitted when generating configure script:
AC_CACHE_VAL(ax_cpu_freq, ...): suspicious cache-id, must contain _cv_
to be cached
I'll wait with this one for the existing PR #292 to be merged first
=> Fix AC_CACHE_VAL warning

m4/ax_c_float_words_bigendian.m4
Commit 23be7ccd7f306fbc73b3f33e2f5ead716d120eef "Fix AX_C_FLOAT_WORDS_BIGENDIAN fails whenever interprocedural optimization is enabled." introduced a regression on the Emscripten target because it switched from grepping the object file where the float definitely will live, to grepping aclocal$EXEEXT which in the case of Emscripten will be aclocal.js but the float is in aclocal.wasm. This problem is unique to Emscripten, it is not present on any other webassembly platform.
To fix, grep `conftest*` for the float.
=> AX_C_FLOAT_WORDS_BIGENDIAN: fix bug with Emscripten target

m4/ax_code_coverage.m4
Not all operating systems have libgcov as a separate library.  Only add the library flag if the symbol is not already available.
=> Make use of libgcov conditional.
