m4/ax_check_enable_debug.m4
m4/ax_compiler_flags.m4
m4/ax_compiler_flags_cflags.m4
m4/ax_compiler_flags_cxxflags.m4
m4/ax_compiler_flags_gir.m4
m4/ax_compiler_flags_ldflags.m4

Various tweaks and fixes to AX_COMPILER_FLAGS

---

m4/ax_lib_postgresql.m4

This is the rebased version of pull https://github.com/peti/autoconf-archive/pull/31

ax_lib_postgresql: add a _LIBS convenience variable and fix version checking

---

m4/ax_check_gnu_make.m4

Look for make using the current environment instead of spawning a new shell.
Extract the GNU Make version and store it into a variable.

Look for make using the current environment instead of spawning a new shell

---

m4/ax_prog_javah.m4

Only a minor fix but will help me to distribute my JNI library.

Added support for the MSYS2/mingw system.

---

m4/ax_code_coverage.m4
m4/ax_valgrind_check.m4

Support multiple directories being passed to CODE_COVERAGE_DIRECTORY.

AX_CODE_COVERAGE: Support multiple directories to extract coverage data

---

m4/ax_count_cpus.m4

Update includes:
* General shell compatibility improvements
* Silent "command not found" messages on non-standard or old shells
* Improved support for various platforms
* NetBSD improved support and tested on NetBSD

AX_COUNT_CPUS update

---

m4/ax_gcc_func_attribute.m4

This was a recent addition to GCC

Add returns_nonnull to ax_gcc_func_attributes.m4

---

m4/ax_boost_chrono.m4

(This is pretty self-explanatory, I suspect...)

Correct library name of Boost.Chrono

---

m4/ax_check_aligned_access_required.m4

Square brackets were overquoted. Avoid square brackets, use quadrigraph
for "#".
Invert the logic so that a crash in the test would count as "yes" for the
aligned address requirement.
When cross-compiling, assume that address alignment is needed, warn the
user.
Use AC_RUN_IFELSE and AC_LANG_PROGRAM, they use sane quoting and take
care of the main function.
Don't include stdio.h, it's not needed for malloc() or anything else.

Improve AX_CHECK_ALIGNED_ACCESS_REQUIRED

---

m4/ax_code_coverage.m4

There is no variable with name CODE_COVERAGE_GENHTML_OPTIONS_DEFAULTS so
use the CODE_COVERAGE_GENHTML_OPTIONS_DEFAULT variable instead

Fix initialization of CODE_COVERAGE_GENHTML_OPTIONS

---

m4/ax_code_coverage.m4

Signed-off-by: Philip Withnall <withnall@endlessm.com>

ax_code_coverage: Fix a recursive variable definition

---

m4/ax_boost_process.m4

This is based on ax_boost_system.m4 serial 20 with the following changes:
* set serial to 1
* replace "system" with "process"
* replace "want_boost" with "want_boost_process"
* a different AC_COMPILE_IFELSE
Used in: https://github.com/bitcoin/bitcoin/pull/15382
I don't pretend to fully understand what I'm doing here, so please check carefully before merging :-)

Add ax_boost_process

---

m4/ax_gcc_builtin.m4

Add x86 builtins related to cpuid support to AX_GCC_BUILTIN.

Add __builtin_cpu_supports and friends to AX_GCC_BUILTIN

---

m4/ax_prog_robot.m4

- fix issue when two numbers version (X.Y) is not detected

AX_PROG_ROBOT: fix version checking

---

m4/ax_path_bdb.m4

Hi,
It seems you do not answer from a mail from january. So open a pull request here.
Bastien

path_bdd from debian

---

m4/ax_prototype.m4

Fix deprecated things in ax_prototype.m4, other small changes.

Fix deprecated things in ax_prototype.m4

---

m4/ax_prog_fasm.m4
m4/ax_prog_fasm_opt.m4
m4/ax_prog_hla.m4
m4/ax_prog_hla_opt.m4
m4/ax_prog_masm.m4
m4/ax_prog_masm_opt.m4
m4/ax_prog_nasm.m4
m4/ax_prog_nasm_opt.m4
m4/ax_prog_tasm.m4
m4/ax_prog_tasm_opt.m4
m4/ax_prog_yasm.m4
m4/ax_prog_yasm_opt.m4

Portability and readbility improvements to macros searching for assemblers and those checking for assemblers' command-line options.

Portability improvements to assembly-related macros

---

m4/ax_have_qt.m4
m4/ax_lib_mysql.m4
m4/ax_lua.m4

Could tou apply the following pathches from debian
Thanks

Fromdebian

---

m4/ax_python.m4
m4/ax_python_devel.m4

Hi,
Could you please merge
Thanks you

Fromdebianpython

---

.github/workflows/autoconf-archive.yml
.gitignore

I used the GitHub Actions Exporter for this, but it took some manual massaging to get it to work properly, though...

Convert Travis CI workflow to GitHub CI workflow

---

m4/ax_python_devel.m4

ax_python_devel will fail the autoconf run if it doesn't detect that a python development environment is available.  That's not always what the user wants, they may want to go on without the functionality.
This change adds a way to pass in an option to specify if you want it to fail or go on if the functionality is not found.  The default is to fail, as before.
This is probably not the right way to do this, but I'm far from an expert in these things.  Hopefully it at least helps.

ax_python_devel: Add an option to make it optional
